# -*- coding: utf-8 -*-
"""Copy of Test0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ERjUNC9gUFGToxSHhsKwXl1YgZ9SM3__

# New Section
"""

import pandas as pd

foo = [3.14, 'pi', 2.718]

series = pd.Series(foo)

df = pd.read_csv('/content/StockData.csv')
# df.iloc[[0, 1]]
df.iloc[:5]



import pandas as pd

df = pd.read_csv('/content/sample_data/california_housing_test.csv')

age_filtered = df[df["Age"] > 23]

result = df.age_filtered

items = {'col1':[1,2,3], 'col2':[2,4,5]}
pd.DataFrame(items)

import pandas as pd

df = pd.read_csv('data.csv')

age_filtered = df["Age"] > 23

result = df[age_filtered]

import pandas as pd

df = pd.read_csv('data.csv')

group = df.groupby('Sex')

min_age = group["Age"].min()

import pandas as pd

df = pd.read_csv('data.csv')

merged = df.merge(df, on='Sex', how='inner')

import numpy as np


sales_data = [200, 450, 150, 400, 500, 700]

sales_array = np.array(sales_data)

min_index = np.argmin(sales_array)

max_index = np.argmax(sales_array)

import numpy as np

sales_data = np.array([100, 150, 200, 250, 300])

new_sale = 350

updated_sales_data = np.append(sales_data, new_sale)

import numpy as np

team_a_scores = np.array([80, 85, 90, 95, 100])

team_b_scores = np.array([70, 75, 80, 85, 90])

all_team_scores = np.concatenate((team_a_scores, team_b_scores))

import numpy as np

daily_temperatures = np.array([72, 75, 78, 70, 68])

total_temperature = np.sum(daily_temperatures)

import numpy as np

exam_scores  = np.array([85, 90, 88, 92, 87])

average_score = np.mean((exam_scores))

"""# New Section"""

import numpy as np

exam_scores  = np.array([85, 90, 88, 92, 87])

average_score = np.mean(exam_scores)

import numpy as np

age_data = np.array([25, 30, 35, 40, 45])

median_age = np.median (age_data)

import numpy as np

sales_data  = [150, 200, 250, 300, 350]

array = np.array(sales_data)

sliced_array = array[1:4]


print(sliced_array)

import numpy as np
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[0:3, 1:3]

import numpy as np
demo_array = np.array([1,2,3,4,5,6,7,8,9,10])
demo_array[0:7] = 5
print(demo_array)

import numpy as np
demo_array = np.arange(0,10)
demo_array<3

import numpy as np
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']

import pandas as pd

mydict = [{'customer': 1, 'category': 2, 'sales': 3, 'd': 4},
          {'customer': 2, 'category': 'data', 'sales': 30, 'd': 400},
          {'customer': 3, 'category': 'data', 'sales': 3000, 'd': 4000},
          {'customer': 4, 'category': 'data2', 'sales': 3100, 'd': 4000},
          {'customer': 5, 'category': 'data2', 'sales': 400, 'd': 4000}
          ]
data_customer = pd.DataFrame(mydict)
# data_customer['category'].value_counts()
# data_customer.sort_values(by='sales',ascending=True)
# data_customer.loc[1:3,['customer','sales']]
# data_customer.loc[1:3, ['customer', 'sales']]
# data_customer.loc[[1,2], ['customer', 'sales']]
# data_customer.groupby(['customer'])['sales'].mean()
# data_customer.groupby(['sales'])['customer'].mean()
foo = data_customer.drop('d', axis = 1)
foo